# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1) Authenticate using the SA key from Secret Manager
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    id: "Authenticate"
    entrypoint: "bash"
    env:
      - "TF_SA_KEY"
    args:
      - "-c"
      - |
        echo "$TF_SA_KEY" > /workspace/sa-key.json
        gcloud auth activate-service-account \
          --key-file=/workspace/sa-key.json

  # 2) Terraform init
  - name: "hashicorp/terraform:1.5.0"
    id: "Init"
    dir: "bootstrap"
    args:
      - "init"
      - "-input=false"

  # 3) Terraform plan
  - name: "hashicorp/terraform:1.5.0"
    id: "Plan"
    dir: "bootstrap"
    args:
      - "plan"
      - "-out=tfplan"

  # 4) Terraform apply
  - name: "hashicorp/terraform:1.5.0"
    id: "Apply"
    dir: "bootstrap"
    args:
      - "apply"
      - "-input=false"
      - "-auto-approve"
      - "tfplan"

availableSecrets:
  secretManager:
    - versionName: "projects/poc-landing-zone-65357/secrets/TF_BUILDER_KEY/versions/latest"
      env: "TF_SA_KEY"
